version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=videoservice
      - POSTGRESQL_PASSWORD=videoservice
      - POSTGRESQL_DATABASE=videoservice
    volumes:
      - './postgresql-master-1:/bitnami/postgresql'
  applications:
    image: 'guneetginnigarg/video-data-service:0.0.1-SNAPSHOT'
    ports:
      - '8080:8080'
    depends_on:
      - postgresql
    volumes:
      - './properties:/config/'
    environment:
      - BOOTAPP_OPTS=-Dspring.config.location=/config/application.properties